Add configurable syncWord, Fix #5
wdomski/SX1278 pull request #7
Opened 2020-12-25 20:06 UTC by HamzaHajeir

Hi

Thanks for the library,

This PR adds a configurable syncWord : 0x12 beside LoRaWAN's 0x34, Aims for compatibility with other's libraries.

2023-12-12 15:12 UTC, wdomski requested changes

2023-12-12 15:12 UTC, wdomski commented on driver/SX1278.h
> +    uint8_t sync_word;
Please fix indention

2023-12-12 15:12 UTC, wdomski commented on driver/SX1278.c
> +    module->sync_word = sync_word;
Please fix indention.

2026-04-26 09:13 UTC, HamzaHajeir commented
Seems that I didn't notice your request backthen and you've already added it. Closing the PR

2026-04-26 09:13 UTC, closed without merging